[package]
name = "libc"
version = "0.2.181"
keywords = ["libc", "ffi", "bindings", "operating", "system"]
categories = ["external-ffi-bindings", "no-std", "os"]
exclude = ["/ci/*", "/.github/*", "/.cirrus.yml", "/triagebot.toml", "cherry-pick-stable.sh"]
description = "Raw FFI bindings to platform libraries like libc."
authors = ["The Rust Project Developers"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/libc"
rust-version = "1.63"

[package.metadata.docs.rs]
features = ["extra_traits"]
default-target = "x86_64-unknown-linux-gnu"
targets = [
    # Note: Keep this in sync with ci/verify-build.py
    #
    # Tier 1
    "aarch64-apple-darwin",
    "aarch64-pc-windows-msvc",
    "aarch64-unknown-linux-gnu",
    "i686-pc-windows-msvc",
    "i686-unknown-linux-gnu",
    "x86_64-pc-windows-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    #
    # Tier 2 with host tools
    "aarch64-pc-windows-gnullvm",
    "aarch64-unknown-linux-musl",
    "aarch64-unknown-linux-ohos",
    "arm-unknown-linux-gnueabi",
    "arm-unknown-linux-gnueabihf",
    "armv7-unknown-linux-gnueabihf",
    "armv7-unknown-linux-ohos",
    "i686-pc-windows-gnu",
    "loongarch64-unknown-linux-gnu",
    "loongarch64-unknown-linux-musl",
    "powerpc-unknown-linux-gnu",
    "powerpc64-unknown-linux-gnu",
    "powerpc64le-unknown-linux-gnu",
    "powerpc64le-unknown-linux-musl",
    "riscv64gc-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "sparcv9-sun-solaris",
    "x86_64-apple-darwin",
    "x86_64-pc-solaris",
    "x86_64-pc-windows-gnullvm",
    "x86_64-unknown-freebsd",
    "x86_64-unknown-illumos",
    "x86_64-unknown-linux-musl",
    "x86_64-unknown-linux-ohos",
    "x86_64-unknown-netbsd",
    #
    # Tier 2 without host tools
    "aarch64-apple-ios",
    "aarch64-apple-tvos",
    "aarch64-apple-visionos",
    "aarch64-apple-watchos",
    "aarch64-linux-android",
    "aarch64-unknown-fuchsia",
    "arm-linux-androideabi",
    "arm-unknown-linux-musleabi",
    "arm-unknown-linux-musleabihf",
    "arm64ec-pc-windows-msvc",
    "armv5te-unknown-linux-gnueabi",
    "armv5te-unknown-linux-musleabi",
    "armv7-linux-androideabi",
    "armv7-unknown-linux-musleabihf",
    "i586-unknown-linux-gnu",
    "i586-unknown-linux-musl",
    "i686-linux-android",
    "i686-unknown-freebsd",
    "i686-unknown-linux-musl",
    "nvptx64-nvidia-cuda",
    "riscv64gc-unknown-linux-musl",
    "sparc64-unknown-linux-gnu",
    "thumbv7neon-linux-androideabi",
    "thumbv7neon-unknown-linux-gnueabihf",
    "wasm32-unknown-emscripten",
    "wasm32-unknown-unknown",
    "wasm32-wasip1",
    "wasm32-wasip2",
    "x86_64-fortanix-unknown-sgx",
    "x86_64-linux-android",
    "x86_64-unknown-fuchsia",
    "x86_64-unknown-linux-gnux32",
    "x86_64-unknown-redox",
    #
    # Tier 3 targets that are distinct enough to be useful, or have historically
    # been documented.
    "aarch64-unknown-freebsd",
    "aarch64-unknown-hermit",
    "aarch64-unknown-illumos",
    "aarch64-unknown-netbsd",
    "aarch64-unknown-nto-qnx800",
    "aarch64-unknown-openbsd",
    "aarch64-unknown-redox",
    "aarch64-wrs-vxworks",
    "aarch64_be-unknown-linux-gnu",
    "aarch64_be-unknown-linux-musl",
    "armebv7r-none-eabi",
    "armebv7r-none-eabihf",
    "armv7-linux-androideabi",
    "armv7-wrs-vxworks-eabihf",
    "armv7r-none-eabi",
    "armv7r-none-eabihf",
    "hexagon-unknown-linux-musl",
    "i686-unknown-haiku",
    "i686-unknown-netbsd",
    "i686-unknown-openbsd",
    "i686-wrs-vxworks",
    "mips-unknown-linux-gnu",
    "mips-unknown-linux-musl",
    "mips64-unknown-linux-gnuabi64",
    "mips64-unknown-linux-muslabi64",
    "mips64el-unknown-linux-gnuabi64",
    "mips64el-unknown-linux-muslabi64",
    "mipsel-sony-psp",
    "mipsel-unknown-linux-gnu",
    "mipsel-unknown-linux-musl",
    "powerpc-unknown-linux-gnuspe",
    "powerpc-unknown-netbsd",
    "powerpc-wrs-vxworks",
    "powerpc-wrs-vxworks-spe",
    "powerpc64-ibm-aix",
    "powerpc64-unknown-freebsd",
    "powerpc64-unknown-linux-gnu",
    "powerpc64-unknown-linux-musl",
    "powerpc64-wrs-vxworks",
    "riscv32-wrs-vxworks",
    "riscv32gc-unknown-linux-musl",
    "riscv32i-unknown-none-elf",
    "riscv32imac-unknown-none-elf",
    "riscv32imc-unknown-none-elf",
    "riscv64-wrs-vxworks",
    "riscv64gc-unknown-freebsd",
    "riscv64gc-unknown-hermit",
    "riscv64gc-unknown-none-elf",
    "riscv64imac-unknown-none-elf",
    "s390x-unknown-linux-musl",
    "sparc-unknown-linux-gnu",
    "sparc64-unknown-netbsd",
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv7m-none-eabi",
    "wasm32-wasip3",
    "x86_64-apple-ios",
    "x86_64-pc-cygwin",
    "x86_64-unknown-dragonfly",
    "x86_64-unknown-haiku",
    "x86_64-unknown-hermit",
    "x86_64-unknown-hurd-gnu",
    "x86_64-unknown-l4re-uclibc",
    "x86_64-unknown-openbsd",
    "x86_64-wrs-vxworks"
]
cargo-args = ["-Zbuild-std=core"]

[dependencies]
rustc-std-workspace-core = { version = "1.0.1", optional = true }

[features]
default = ["std"]
std = []
rustc-dep-of-std = ['align', 'rustc-std-workspace-core']
extra_traits = []

# `const-extern-function` is deprecated and no longer does anything
const-extern-fn = []

# `align` is deprecated and no longer does anything
align = []

# use_std is deprecated, use `std` instead
use_std = ['std']

[workspace]
members = [
    "ctest",
    "libc-test",
]

# FIXME(msrv): These should be renamed as `[workspace.lints.*]` once MSRV is above 1.64
#       This way all crates can use it with `[lints] workspace=true` section

[lints.rust]
# FIXME(cleanup): make ident usage consistent in each file
unused_qualifications = "allow"

[lints.clippy]
# Enable pedantic lints - use this manually once in a while, but don't enable by default
# pedantic = { level = "warn", priority = -1 }

# We are okay with the current state of these lints
explicit_iter_loop = "warn"
identity_op = "allow"  # some expressions like `0 | x` are clearer for bit ops
manual_assert = "warn"
map_unwrap_or = "warn"
missing_safety_doc = "allow"  # safety? in libc? seriously?
non_minimal_cfg = "allow"  # for some reason cfg_if! sometimes trigger this
ptr_as_ptr = "warn"
unnecessary_semicolon = "warn"

# FIXME(clippy): these should be fixed if possible
expl_impl_clone_on_copy = "allow"
uninlined_format_args = "allow"
unnecessary_cast = "allow"  # some casts like `as usize` are only needed for some targets
used_underscore_binding = "allow"

[package.metadata.cargo-semver-checks.lints]
# Alignment is an internal detail that users must not rely upon
repr_align_removed = "warn"
# We deprecate things all the time
global_value_marked_deprecated = "warn"
