[relabel]
allow-unauthenticated = [
    "C-*",
    "O-*",
    "S-*",
    "stable-nominated",
]

[assign]
contributing_url = "https://github.com/rust-lang/libc/blob/HEAD/CONTRIBUTING.md"

[assign.owners]
"*" = [
    "@JohnTitor",
    "@tgross35",
]

[autolabel."A-CI"]
trigger_files = [
    ".cirrus.yml",
    ".github",
    "src/ci",
]

[autolabel."S-waiting-on-review"]
new_pr = true

[autolabel."O-android"]
trigger_files = ["src/unix/linux_like/android"]

[autolabel."O-arm"]
trigger_files = [
    "src/solid/arm.rs",
    "src/unix/bsd/freebsdlike/freebsd/arm.rs",
    "src/unix/bsd/netbsdlike/netbsd/arm.rs",
    "src/unix/bsd/netbsdlike/openbsd/arm.rs",
    "src/unix/linux_like/android/b32/arm.rs",
    "src/unix/linux_like/linux/gnu/b32/arm/",
    "src/unix/linux_like/linux/musl/b32/arm/",
    "src/unix/linux_like/linux/uclibc/arm/",
    "src/unix/newlib/arm/",
    "src/vxworks/arm.rs",
]

[autolabel."O-bsd"]
trigger_files = ["src/unix/bsd/mod.rs"]

[autolabel."O-dragonfly"]
trigger_files = ["src/unix/bsd/freebsdlike/dragonfly"]

[autolabel."O-gnu"]
trigger_files = [
    "src/unix/linux_like/linux/gnu",
    "src/windows/gnu",
]

[autolabel."O-illumos"]
trigger_files = ["src/unix/solarish/illumos.rs"]

[autolabel."O-linux"]
trigger_files = ["src/unix/linux_like/linux"]

[autolabel."O-linux-like"]
trigger_files = ["src/unix/linux_like/mod.rs"]

[autolabel."O-macos"]
trigger_files = ["src/unix/bsd/apple"]

[autolabel."O-mips"]
trigger_files = [
    "src/unix/bsd/netbsdlike/netbsd/mips.rs",
    "src/unix/bsd/netbsdlike/openbsd/mips64.rs",
    "src/unix/linux_like/linux/arch/mips",
    "src/unix/linux_like/linux/gnu/b32/mips",
    "src/unix/linux_like/linux/gnu/b64/mips64",
    "src/unix/linux_like/linux/musl/b32/mips",
    "src/unix/linux_like/linux/musl/b64/mips64.rs",
    "src/unix/linux_like/linux/uclibc/mips",
]

[autolabel."O-musl"]
trigger_files = ["src/unix/linux_like/linux/musl"]

[autolabel."O-newlib"]
trigger_files = ["src/unix/newlib"]

[autolabel."O-redox"]
trigger_files = ["src/unix/redox"]

[autolabel."O-riscv"]
trigger_files = [
    "src/fuchsia/riscv64.rs",
    "src/unix/bsd/freebsdlike/freebsd/riscv64.rs",
    "src/unix/bsd/netbsdlike/netbsd/riscv64.rs",
    "src/unix/bsd/netbsdlike/openbsd/riscv64.rs",
    "src/unix/linux_like/android/b64/riscv64",
    "src/unix/linux_like/linux/gnu/b32/riscv32",
    "src/unix/linux_like/linux/gnu/b64/riscv64",
    "src/unix/linux_like/linux/musl/b32/riscv32",
    "src/unix/linux_like/linux/musl/b64/riscv64",
    "src/vxworks/riscv32.rs",
    "src/vxworks/riscv64.rs",
]

[autolabel."O-solarish"]
trigger_files = ["src/unix/solarish"]

[autolabel."O-sparc"]
trigger_files = [
    "src/unix/bsd/netbsdlike/netbsd/sparc64.rs",
    "src/unix/bsd/netbsdlike/openbsd/sparc64.rs",
    "src/unix/linux_like/linux/arch/sparc",
    "src/unix/linux_like/linux/gnu/b32/sparc",
    "src/unix/linux_like/linux/gnu/b64/sparc64",
]

[autolabel."O-unix"]
trigger_files = ["src/unix"]

[autolabel."O-wasi"]
trigger_files = ["src/wasi"]

[autolabel."O-windows"]
trigger_files = ["src/windows"]

[autolabel."O-x86"]
trigger_files = [
    "src/fuchsia/x86_64.rs",
    "src/unix/bsd/apple/b64/x86_64",
    "src/unix/bsd/freebsdlike/freebsd/freebsd12/x86_64.rs",
    "src/unix/bsd/freebsdlike/freebsd/freebsd13/x86_64.rs",
    "src/unix/bsd/freebsdlike/freebsd/freebsd14/x86_64.rs",
    "src/unix/bsd/freebsdlike/freebsd/freebsd15/x86_64.rs",
    "src/unix/bsd/freebsdlike/freebsd/x86.rs",
    "src/unix/bsd/freebsdlike/freebsd/x86_64",
    "src/unix/bsd/netbsdlike/netbsd/x86.rs",
    "src/unix/bsd/netbsdlike/netbsd/x86_64.rs",
    "src/unix/bsd/netbsdlike/openbsd/x86.rs",
    "src/unix/bsd/netbsdlike/openbsd/x86_64.rs",
    "src/unix/haiku/x86_64.rs",
    "src/unix/linux_like/android/b32/x86",
    "src/unix/linux_like/android/b64/x86_64",
    "src/unix/linux_like/linux/gnu/b32/x86",
    "src/unix/linux_like/linux/gnu/b64/x86_64",
    "src/unix/linux_like/linux/musl/b32/x86",
    "src/unix/linux_like/linux/musl/b64/x86_64",
    "src/unix/linux_like/linux/uclibc/x86_64",
    "src/unix/nto/x86_64.rs",
    "src/unix/solarish/x86.rs",
    "src/unix/solarish/x86_64.rs",
    "src/unix/solarish/x86_common.rs",
    "src/vxworks/x86.rs",
    "src/vxworks/x86_64.rs",
]

[review-submitted]
# These labels are removed when a review is submitted.
review_labels = ["S-waiting-on-review"]
# This label is added when a review is submitted.
reviewed_label = "S-waiting-on-author"

[review-requested]
# Those labels are removed when PR author requests a review from an assignee
remove_labels = ["S-waiting-on-author"]
# Those labels are added when PR author requests a review from an assignee
add_labels = ["S-waiting-on-review"]

[shortcut]

[mentions."src/unix/bsd/netbsdlike/openbsd"]
message = "Some changes occurred in OpenBSD module"
cc = ["@semarie"]

[mentions."src/unix/bsd/netbsdlike/mod.rs"]
message = "Some changes occurred in OpenBSD module"
cc = ["@semarie"]

[mentions."src/unix/solarish"]
message = "Some changes occurred in solarish module"
cc = ["@jclulow", "@pfmooney"]
