[package]
name = "ctest"
version = "0.2.8"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/ctest"
homepage = "https://github.com/alexcrichton/ctest"
documentation = "https://docs.rs/ctest"
description = """
Automated tests of FFI bindings.
"""

[dependencies]
syntex_syntax = "0.59.1"
cc = "1.0.1"

[workspace]
members = ["testcrate"]
