[package]
name = "libc-test"
version = "0.2.151"
authors = ["The Rust Project Developers"]
license = "MIT OR Apache-2.0"
build = "build.rs"
repository = "https://github.com/rust-lang/libc"
homepage = "https://github.com/rust-lang/libc"
description = """
A test crate for the libc crate.
"""

[dependencies.libc]
path = ".."
version = "0.2.151"
default-features = false

[build-dependencies]
cc = "1.0.83"
# FIXME: Use fork ctest until the maintainer gets back.
ctest2 = "0.4.3"

[features]
default = ["std"]
std = ["libc/std"]
align = ["libc/align"]
extra_traits = ["libc/extra_traits"]

[[test]]
name = "main"
path = "test/main.rs"
harness = false

[[test]]
name = "linux-fcntl"
path = "test/linux_fcntl.rs"
harness = false

[[test]]
name = "linux-if-arp"
path = "test/linux_if_arp.rs"
harness = false

[[test]]
name = "linux-ipv6"
path = "test/linux_ipv6.rs"
harness = false

[[test]]
name = "linux-elf"
path = "test/linux_elf.rs"
harness = false

[[test]]
name = "linux-strerror_r"
path = "test/linux_strerror_r.rs"
harness = false

[[test]]
name = "linux-termios"
path = "test/linux_termios.rs"
harness = false

[[test]]
name = "cmsg"
path = "test/cmsg.rs"
harness = true

[[test]]
name = "makedev"
path = "test/makedev.rs"
harness = true

[[test]]
name = "errqueue"
path = "test/errqueue.rs"
harness = true

[[test]]
name = "sigrt"
path = "test/sigrt.rs"
harness = true

[[test]]
name = "semver"
path = "test/semver.rs"
harness = false
