[package]
name = "libc-test"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[dependencies]
libc = { path = ".." }

[build-dependencies]
ctest = { git = "https://github.com/alexcrichton/ctest" }

[[test]]
name = "main"
path = "test/main.rs"
harness = false

[[test]]
name = "linux-fcntl"
path = "test/linux_fcntl.rs"
harness = false
